name: Generate VFS files

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get repository
        run: |
          git clone https://github.com/PK2-W/community-episodes.git . -b master
          git config user.email "bumxu@users.noreply.github.com"
          git config user.name "octocat"
          git fetch

      - name: Switch to release branch
        run: |
          git checkout --track origin/public
          git branch -vv

      - name: Updtate with changes
        run: |
          git merge --no-ff master
        
      - name: Clean generated files
        run: |
          rm -R *
          git checkout --theirs master .
     
      - name: Generate VFS files
        run: |
          npm install
          npm run generate-vfs

      - name: Commit
        id: commit
        run: |
          git add **/vfs.json -f
          git diff-index --quiet HEAD || git commit -a -m "Automatic actions"

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: public
