# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Add dummy
        run: |
          uuidgen > random.txt
          pwd
          cat random.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Required
          commit_message: Workflow testing

          # Optional branch to push to, defaults to the current branch
          branch: public

          # Optional options appended to `git-commit`
          # See https://git-scm.com/docs/git-commit for a list of available options
          #commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: ./**/*.txt

          # Optional local file path to the repository
          #repository: .

          # Optional commit user and author settings
          #commit_user_name: octocat
          #commit_user_email: octocat@example.org
          #commit_author: Octocat <actions@github.com>

          # Optional tag message 
          # Action will create and push a new tag to the remote repository and the defined branch
          #tagging_message: 'v1.0.0'

          # Optional options appended to `git-push`
          # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
          #push_options: '--force'

          # Optional: Disable dirty check and always try to create a commit and push
          #skip_dirty_check: true
